<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * ChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChallengeRepository extends \Doctrine\ORM\EntityRepository
{
	public function findUserChallenges($userId)
	{
		return $this->getEntityManager()
			->createQuery(
				"Select u.name, u.lastName, c.clubName, ch.date, ch.time, ch.id, ch.status 
				from AppBundle:Usuario u, AppBundle:Club c, AppBundle:Challenge ch 
				where ch.player2 = $userId and c.id = ch.club and u.id = ch.player2 and ch.status is NULL"
			)
			->getResult();
	}

	public function findMyChallenges($userId)
	{
		return $this->getEntityManager()
			->createQuery(
				"Select u.name, u.lastName, c.clubName, ch.date, ch.time, ch.id, ch.status 
				from AppBundle:Usuario u, AppBundle:Club c, AppBundle:Challenge ch 
				where ch.player1 = $userId and c.id = ch.club and u.id = ch.player2"
			)
			->getResult();
	}

	public function insertToMatch($idChallenge)
	{
		return $this->getEntityManager()
		->createQuery(
			"Insert into match (player1, player2, club, date, time)
			(Select player1, player2, club, date, time
			from challenge where id = idChallenge)"
		)
		->getResult();
	}

}
